app:
  service1:
    serviceProps:
      serviceBaseUrl: "http://localhost:"
      servicePort: 8082
      endpoints: 
        getUsers: /getusers
        addNewUser: /addnewuser
        getUser: /getuser/{name}
        modifyUser: /modifyuser
